version: 0.0.0

server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: NON_NULL
  application:
    name: financial-api
  profiles:
    active: "development"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${FINANCIAL_DB_USER}
    password: ${FINANCIAL_DB_PWD}
    url: jdbc:postgresql://localhost:${FINANCIAL_DB_PORT}/${FINANCIAL_DB_DATABASE}

redis:
  host: 127.0.0.1
  port: 1122
  types: redis